### ISSUE TITLE
Doesn't work out of the box because colors aren't defined

### ISSUE THREAD

**Issue by 2rs2ts** [mKaloer/powerline_mem_segment#9]
```
ImportError: Failed to obtain segment function
2020-07-11 14:59:18,098:ERROR:tmux:mem_usage:Failed to set highlight group: 'Highlighting groups not found in colorscheme: mem_usage_gradient, mem_usage'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/powerline/segment.py", line 151, in set_segment_highlighting
    segment.get('gradient_level')
  File "/usr/lib/python3/dist-packages/powerline/colorscheme.py", line 105, in get_highlighting
    raise KeyError('Highlighting groups not found in colorscheme: ' + ', '.join(groups))
KeyError: 'Highlighting groups not found in colorscheme: mem_usage_gradient, mem_usage'
```

Above error is from my daemon. I am a new powerline user so I don't know if I did anything that's obviously wrong to an experienced user but your README doesn't mention having to add these to colors.json or anything, so if this is something one has to set up manually, I think it should be documented.

**Comment by 2rs2ts** [comment]
Haha, disregard me. I literally missed it in the readme.
